CREATE TABLE clients (
    session_name VARCHAR(100) PRIMARY KEY,
    token VARCHAR(255),
    available_credits INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);